name: mse_yonsei
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  device_preview: ^1.0.0
  provider: ^6.0.1
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  drag_and_drop_lists: ^0.3.1
  expandable_tree_menu: ^0.1.0-dev.5
  flutter_dialpad: ^1.0.1
  url_launcher: ^6.0.18
  firebase_auth: ^3.3.5
  firebase_core: ^1.3.0
  shimmer: ^2.0.0
  flutter_svg: ^0.22.0
  extended_image: ^6.0.1
  cloud_firestore: ^1.0.7
  flutter_phone_direct_caller: ^2.0.0
  flutter_arc_speed_dial: ^2.0.0
  intro_slider: ^3.0.2
  rxdart: ^0.27.2
  flash: ^2.0.3+2
  flutter_launcher_icons: ^0.9.2
  upgrader: ^3.12.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/yonsei_mse.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: DonghyunKo
      fonts:
        - asset: assets/fonts/BMYEONSUNG_ttf.ttf
    - family: DonghyunEn
      fonts:
        - asset: assets/fonts/Cinzel-Regular.ttf

