import 'package:mse_yonsei/inner_list.dart';
import 'package:mse_yonsei/model/firestore/post_model.dart';

class ItemList {
  List<InnerList> _list = [
    // YONSEI
    InnerList(
      name: 'Yonsei',
      children: [
        PostModel(
          name: '커리어 연세',
          phone_number: '',
          url: 'https://career.yonsei.ac.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '런어스',
          phone_number: '',
          url: 'https://www.learnus.org/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '학술정보원(도서관)',
          phone_number: '',
          url: 'https://library.yonsei.ac.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '연세 포탈',
          phone_number: '',
          url: 'https://portal.yonsei.ac.kr/main/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '연세대학교',
          phone_number: '',
          url: 'https://www.yonsei.ac.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
      ],
    ),
    // YONSEI MSE
    InnerList(
      name: 'Yonsei MSE',
      children: [
        PostModel(
          name: '행사 및 소식(장학금)',
          phone_number: '',
          url: 'https://mse.yonsei.ac.kr/mse/board/news.do',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '신소재공학과',
          phone_number: '',
          url: 'https://mse.yonsei.ac.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '공지사항',
          phone_number: '',
          url: 'https://mse.yonsei.ac.kr/mse/board/notice.do',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '교수님 목록',
          phone_number: '',
          url: 'https://mse.yonsei.ac.kr/mse/board/organization.do',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
      ],
    ),
    // PROFESSOR
    InnerList(
      name: 'Professor & Lab',
      children: [
        PostModel(
          name: '유기차세대반도체연구실',
          phone_number: '',
          url: '',
          lab_url: 'https://keehoonkang.wixsite.com/onelab',
          lab_name: '',
          professor_url:
              'https://mse.yonsei.ac.kr/faculty/name_search.do?mode=view&userId=6bVRytHawxga7ystNgXKSg%3D%3D&sosokcd=1012731',
          professor_name: '강기훈 교수님',
          category: 'PROFESSOR',
        ),
        PostModel(
          name: '연성전자재료 및 소자연구실',
          phone_number: '',
          url: '',
          lab_url: 'https://semdl.modoo.at/',
          lab_name: '',
          professor_url:
              'https://mse.yonsei.ac.kr/faculty/name_search.do?mode=view&userId=mW5DiAAyDTaj9eZu%2FHN0Dw%3D%3D&sosokcd=',
          professor_name: '강달영 교수님',
          category: 'PROFESSOR',
        ),
        PostModel(
          name: '반도체연구실',
          phone_number: '',
          url: '',
          lab_url: 'http://semicon.yonsei.ac.kr/main/main.php',
          lab_name: '',
          professor_url:
              'https://mse.yonsei.ac.kr/faculty/name_search.do?mode=view&userId=dLGPLyVJhCTyKqASiyaZ6Q%3D%3D&sosokcd= ',
          professor_name: '고대홍 교수님',
          category: 'PROFESSOR',
        ),
        PostModel(
          name: '에너지변환재료연구실',
          phone_number: '',
          url: '',
          lab_url: 'https://web.yonsei.ac.kr/echemlab/public_html/',
          lab_name: '',
          professor_url:
              'https://mse.yonsei.ac.kr/faculty/name_search.do?mode=view&userId=B%2FKPjCLc16ih0iFMXNjjDg%3D%3D&sosokcd=',
          professor_name: '김광범 교수님',
          category: 'PROFESSOR',
        ),
        PostModel(
          name: '나노구조재료연구실',
          phone_number: '',
          url: '',
          lab_url: 'https://obs.yonsei.ac.kr/nsm/',
          lab_name: '',
          professor_url:
              'https://mse.yonsei.ac.kr/faculty/name_search.do?mode=view&userId=IszGjOH5hVtxtCjS5y8kMw%3D%3D&sosokcd=',
          professor_name: '김도향 교수님',
          category: '',
        ),
        PostModel(
          name: '정보전자재료연구실',
          phone_number: '',
          url: '',
          lab_url: 'https://web.yonsei.ac.kr/iemrlab/',
          lab_name: '',
          professor_url:
              'https://mse.yonsei.ac.kr/faculty/name_search.do?mode=view&userId=FxdYidQPpM9XoJZYWRQarw%3D%3D&sosokcd=',
          professor_name: '명재민 교수님',
          category: 'PROFESSOR',
        ),
        PostModel(
          name: '나노기능재료연구실',
          phone_number: '',
          url: '',
          lab_url: 'http://nfml.yonsei.ac.kr/',
          lab_name: '',
          professor_url:
              'https://mse.yonsei.ac.kr/faculty/name_search.do?mode=view&userId=W4HorUmt3GjDj8VF%2F%2FW7iA%3D%3D&sosokcd=',
          professor_name: '문주호 교수님',
          category: 'PROFESSOR',
        ),
        PostModel(
          name: '고온융체반응시스템연구실',
          phone_number: '',
          url: '',
          lab_url:
              'http://chemical.yonsei.ac.kr/frontpage.asp?catalogid=chemical&language=ko',
          lab_name: '',
          professor_url: '',
          professor_name: '민동준 교수님',
          category: 'PROFESSOR',
        ),
        PostModel(
          name: '웨어러블융합전자연구실',
          phone_number: '',
          url: '',
          lab_url: 'http://wearablelab.net/main/main.php',
          lab_name: '',
          professor_url: '',
          professor_name: '박장웅 교수님',
          category: 'PROFESSOR',
        ),
        PostModel(
          name: '재료계면연구실',
          phone_number: '',
          url: '',
          lab_url: 'https://www.interface.yonsei.ac.kr/',
          lab_name: '',
          professor_url:
              'https://mse.yonsei.ac.kr/faculty/name_search.do?mode=view&userId=mJwHdIri%2FOQ%2Bwq4g7yeHOg%3D%3D&sosokcd=',
          professor_name: '박진우 교수님',
          category: 'PROFESSOR',
        ),
        PostModel(
          name: '나노고분자재료연구실',
          phone_number: '',
          url: '',
          lab_url: 'https://nplcmpark2833.wixsite.com/nanopolymer',
          lab_name: '',
          professor_url:
              'https://mse.yonsei.ac.kr/faculty/name_search.do?mode=view&userId=g595YLV%2Bw4ZLhy0Q%2BxRXLg%3D%3D&sosokcd=',
          professor_name: '박철민 교수님',
          category: 'PROFESSOR',
        ),
        PostModel(
          name: '재료물성연구실',
          phone_number: '',
          url: '',
          lab_url: 'http://mclab.yonsei.ac.kr/',
          lab_name: '',
          professor_url:
              'https://mse.yonsei.ac.kr/faculty/name_search.do?mode=view&userId=ayRGvVm5%2BiEl54BCH%2B8Zig%3D%3D&sosokcd=',
          professor_name: '박형호 교수님',
          category: 'PROFESSOR',
        ),
        PostModel(
          name: '금속강도 및 성형연구실',
          phone_number: '',
          url: '',
          lab_url: '',
          lab_name: '',
          professor_url:
              'https://mse.yonsei.ac.kr/faculty/name_search.do?mode=view&userId=bVPnngZFU79Pq6ID2Rpr3g%3D%3D&sosokcd=',
          professor_name: '배동현 교수님',
          category: 'PROFESSOR',
        ),
        PostModel(
          name: '나노바이오시스템연구실',
          phone_number: '',
          url: '',
          lab_url: '',
          lab_name: '',
          professor_url:
              'https://mse.yonsei.ac.kr/faculty/name_search.do?mode=view&userId=qQbFRRd%2F9e7T9HQwcOvqIg%3D%3D&sosokcd=',
          professor_name: '변재철 교수님',
          category: 'PROFESSOR',
        ),
        PostModel(
          name: 'Materials Theory Group',
          phone_number: '',
          url: '',
          lab_url: 'https://www.materials-theory.org/',
          lab_name: '',
          professor_url:
              'https://mse.yonsei.ac.kr/faculty/name_search.do?mode=view&userId=DMtDOyCh6Jx1IrGmfSLzMg%3D%3D&sosokcd=',
          professor_name: '손알로이시우스 교수님',
          category: 'PROFESSOR',
        ),
        PostModel(
          name: '네오금속공정연구실',
          phone_number: '',
          url: '',
          lab_url: 'https://web.yonsei.ac.kr/exmet/',
          lab_name: '',
          professor_url:
              'https://mse.yonsei.ac.kr/faculty/name_search.do?mode=view&userId=92erNoalrALsmXOpFGbTZg%3D%3D&sosokcd=',
          professor_name: '손일 교수님',
          category: '',
        ),
        PostModel(
          name: '반도체공정연구실',
          phone_number: '',
          url: '',
          lab_url: 'http://sml.ac.kr/main/main.php',
          lab_name: '',
          professor_url:
              'https://mse.yonsei.ac.kr/faculty/name_search.do?mode=view&userId=5SCEPFBaJ6ZK7ENsqt54QA%3D%3D&sosokcd=',
          professor_name: '손현철 교수님',
          category: 'PROFESSOR',
        ),
        PostModel(
          name: '멀티스케일재료연구실',
          phone_number: '',
          url: '',
          lab_url: 'https://www.multiscales.com/',
          lab_name: '',
          professor_url: '',
          professor_name: '심우영 교수님',
          category: 'PROFESSOR',
        ),
        PostModel(
          name: '준안정재료설계연구실',
          phone_number: '',
          url: '',
          lab_url: 'https://wmd-group.github.io/',
          lab_name: '',
          professor_url:
              'https://mse.yonsei.ac.kr/faculty/name_search.do?mode=view&userId=1JIfn6mf6XV4lrO1M1sT%2Bw%3D%3D&sosokcd=',
          professor_name: '월쉬아론 교수님',
          category: 'PROFESSOR',
        ),
        PostModel(
          name: '에너지소재소자연구실',
          phone_number: '',
          url: '',
          lab_url: 'https://www.yonsei-emdl.net/',
          lab_name: '',
          professor_url: '',
          professor_name: '이규형 교수님',
          category: 'PROFESSOR',
        ),
        PostModel(
          name: '광학재료 및 소자연구실',
          phone_number: '',
          url: '',
          lab_url: 'http://optics.yonsei.ac.kr/',
          lab_name: '',
          professor_url:
              'https://mse.yonsei.ac.kr/faculty/name_search.do?mode=view&userId=Aw3rUgSCSd68E1mNz5L8Kg%3D%3D&sosokcd=',
          professor_name: '이명규 교수님',
          category: 'PROFESSOR',
        ),
        PostModel(
          name: '상변태연구실',
          phone_number: '',
          url: '',
          lab_url: 'http://phase.yonsei.ac.kr/',
          lab_name: '',
          professor_url:
              'https://mse.yonsei.ac.kr/faculty/name_search.do?mode=view&userId=Q%2By%2FMNu7B7VkUhde%2FZleIA%3D%3D&sosokcd=',
          professor_name: '이영국 교수님',
          category: 'PROFESSOR',
        ),
        PostModel(
          name: '나노소자연구실',
          phone_number: '',
          url: '',
          lab_url: 'http://spintronics.yonsei.ac.kr/',
          lab_name: '',
          professor_url:
              'https://mse.yonsei.ac.kr/faculty/name_search.do?mode=view&userId=Cnm6vWrTI5dJZq%2Bih0N%2Fgw%3D%3D&sosokcd=1012731',
          professor_name: '이우영 교수님',
          category: 'PROFESSOR',
        ),
        PostModel(
          name: '분자조립바이오소재연구실',
          phone_number: '',
          url: '',
          lab_url: 'https://bionano.yonsei.ac.kr/bionano/',
          lab_name: '',
          professor_url:
              'https://mse.yonsei.ac.kr/faculty/name_search.do?mode=view&userId=Ad%2B6xD178AFHYMfd3wNgeA%3D%3D&sosokcd=',
          professor_name: '임용범 교수님',
          category: 'PROFESSOR',
        ),
        PostModel(
          name: '전자에너지소재연구실',
          phone_number: '',
          url: '',
          lab_url: 'http://eeml.yonsei.ac.kr/',
          lab_name: '',
          professor_url:
              'https://mse.yonsei.ac.kr/faculty/name_search.do?mode=view&userId=knTAXC8iJeUO%2BhAWBug%2B8w%3D%3D&sosokcd=',
          professor_name: '조용수 교수님',
          category: 'PROFESSOR',
        ),
        PostModel(
          name: '나노구조연구실',
          phone_number: '',
          url: '',
          lab_url: 'http://hjchoi.yonsei.ac.kr/',
          lab_name: '',
          professor_url:
              'https://mse.yonsei.ac.kr/faculty/name_search.do?mode=view&userId=bKwZyvqgW7RpiminG0iDBg%3D%3D&sosokcd=',
          professor_name: '최헌진 교수님',
          category: 'PROFESSOR',
        ),
        PostModel(
          name: '스핀소자연구실',
          phone_number: '',
          url: '',
          lab_url: 'https://web.yonsei.ac.kr/smdl/main.html',
          lab_name: '',
          professor_url: '',
          professor_name: '홍종일 교수님',
          category: 'PROFESSOR',
        ),
        PostModel(
          name: '나노에너지신소재연구실',
          phone_number: '',
          url: '',
          lab_url: 'http://anml21.yonsei.ac.kr/',
          lab_name: '',
          professor_url:
              'https://mse.yonsei.ac.kr/faculty/name_search.do?mode=view&userId=t2LGUDWrofGvshcLs81f9w%3D%3D&sosokcd=',
          professor_name: '황성주 교수님',
          category: 'PROFESSOR',
        ),
      ],
    ),
    // PRIVATE_ENTERPRISE
    InnerList(
      name: 'Private_enterprise',
      children: [
        //IDM
        PostModel(
          name: '삼성(IDM)',
          phone_number: '',
          url: 'https://www.samsung.com/sec/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'sk하이닉스(IDM)',
          phone_number: '',
          url: 'https://www.skhynix.com/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '매그나칩(IDM)',
          phone_number: '',
          url: 'https://www.magnachip.com/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '인텔(IDM)',
          phone_number: '',
          url: 'https://www.intel.co.kr/content/www/kr/ko/homepage.html',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'Micron(IDM) ',
          phone_number: '',
          url: 'https://www.micron.com/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '도시바(IDM)',
          phone_number: '',
          url: 'http://www.toshiba.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),

        //Fabless
        PostModel(
          name: 'LX세미콘(Fabless)',
          phone_number: '',
          url: 'https://www.lxsemicon.com/kr/web/main?language=ko',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '텔레칩스(Fabless)',
          phone_number: '',
          url: 'https://www.telechips.com/kor/main/main.php?intro=true',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '넥스트칩(Fabless)',
          phone_number: '',
          url: 'http://www.nextchip.com/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'QUALCOMM(Fabless)',
          phone_number: '',
          url: 'https://www.qualcomm.com/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'MEDIATEK(Fabless)',
          phone_number: '',
          url: 'https://www.mediatek.com/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'AMD(Fabless)',
          phone_number: '',
          url: 'https://www.amd.com/ko',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'NVIDIA(Fabless)',
          phone_number: '',
          url: 'https://www.nvidia.com/ko-kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),

        //Foundry
        PostModel(
          name: '동부하이텍(Foundry)',
          phone_number: '',
          url: 'https://dbhitek.com/kr/default.asp',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'TSMC(Foundry)',
          phone_number: '',
          url: 'https://www.tsmc.com/engsish',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'UMC',
          phone_number: '',
          url: 'https://www.umc.com/en/home/Index',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'SMIC',
          phone_number: '',
          url: 'http://snusmic.com/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'GLOBAL_FOUNDRY',
          phone_number: '',
          url: 'https://gf.com',
          lab_url: '',
          professor_url: '',
          category: '',
        ),

        //Packaging
        PostModel(
          name: '하나마이크론(Packaging)',
          phone_number: '',
          url: 'http://www.hanamicron.com/kor/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'WINPAC(Packaging)',
          phone_number: '',
          url: 'http://www.winpac.co.kr/new2012/index_main.php',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'ASE(Packaging)',
          phone_number: '',
          url: 'https://www.aseglobal.com/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'AMKOR(Packaging)',
          phone_number: '',
          url: 'https://amkor.com/kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'SPIL(Packaging)',
          phone_number: '',
          url: 'https://www.spil.com.tw/index.asp',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'STATSChipPAC(Packaging)',
          phone_number: '',
          url: 'http://www.statschippac.com',
          lab_url: '',
          professor_url: '',
          category: '',
        ),

        //TEST
        PostModel(
          name: '하나마이크론(TEST)',
          phone_number: '',
          url: 'http://www.hanamicron.com/kor/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'STS반도체통신(TEST)',
          phone_number: '',
          url: 'http://www.sfasemicon.com/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'ASE(TEST)',
          phone_number: '',
          url: 'https://www.aseglobal.com/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'AMKOR(TEST)',
          phone_number: '',
          url: 'https://amkor.com/kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'SPIL(TEST)',
          phone_number: '',
          url: 'https://www.spil.com.tw/index.asp',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'STATSChipPAC(TEST)',
          phone_number: '',
          url: 'http://www.statschippac.com/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),

        //장비회사
        PostModel(
          name: '세메스(장비회사)',
          phone_number: '',
          url: 'https://www.semes.com/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '주성엔지니어링(장비회사)',
          phone_number: '',
          url: 'http://www.jusung.com/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '케이씨텍(장비회사)',
          phone_number: '',
          url: 'http://www.kctech.com/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'PSK(장비회사)',
          phone_number: '',
          url: 'https://www.pskinc.com/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '한미반도체(장비회사) ',
          phone_number: '',
          url: 'http://www.hanmisemi.com/_2013dev/main.asp',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'ASML(장비회사)',
          phone_number: '',
          url: 'https://www.asml.com/en',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '램리서치(장비회사)',
          phone_number: '',
          url: 'https://www.lamresearch.com/ko/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'TEL(장비회사)/',
          phone_number: '',
          url: 'https://www.tel.com',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'KLA_TENCOR(장비회사)',
          phone_number: '',
          url: 'https://www.kla-tencor.com/ko',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
      ],
    ),
    // GOV_FUND INST.
    InnerList(
      name: 'Gov_fund Inst.',
      children: [
        //서울
        PostModel(
          name: '한국과학기술연구원(서울)',
          phone_number: '',
          url: 'https://www.kist.re.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '한국산업기술진흥원(서울)',
          phone_number: '',
          url: 'https://www.kiat.or.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '한국에너지기술평가원(서울)',
          phone_number: '',
          url: 'https://www.ketep.re.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        //경기도
        PostModel(
          name: '한국철도기술연구원(경기도)',
          phone_number: '',
          url: 'https://www.krri.re.kr/html/kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '고등기술연구원(경기도)',
          phone_number: '',
          url: 'https://www.iae.re.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),

        PostModel(
          name: '전자부품연구원(경기도)',
          phone_number: '',
          url: 'https://www.keti.re.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        // 충청도
        PostModel(
          name: '자동차부품연구원(충청도)',
          phone_number: '',
          url: 'https://www.katech.re.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '한국생산기술연구원(충청도)',
          phone_number: '',
          url: 'https://www.kitech.re.kr/main/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        //대전

        PostModel(
          name: '국방과학연구소(대전)',
          phone_number: '',
          url: 'https://www.add.re.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '한국기계연구원(대전)',
          phone_number: '',
          url: 'https://www.kimm.re.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '한국기초과학지원연구원(대전)',
          phone_number: '',
          url: 'https://www.kbsi.re.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),

        PostModel(
          name: '한국생명공학연구원(대전)',
          phone_number: '',
          url: 'https://www.kribb.re.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),

        PostModel(
          name: '한국원자력연구원(대전)',
          phone_number: '',
          url: 'https://www.kaeri.re.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),

        PostModel(
          name: '한국에너지기술연구원(대전)',
          phone_number: '',
          url: 'https://www.kier.re.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),

        PostModel(
          name: '한국전자통신연구원(대전)',
          phone_number: '',
          url: 'https://www.etri.re.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),

        PostModel(
          name: '한국지질자원연구원(대전)',
          phone_number: '',
          url: 'https://www.kigam.re.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),

        PostModel(
          name: '한국표준과학연구원(대전)',
          phone_number: '',
          url: 'https://www.kriss.re.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),

        PostModel(
          name: '한국항공우주연구원(대전)',
          phone_number: '',
          url: 'https://www.kari.re.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),

        PostModel(
          name: '한국화학연구원(대전)',
          phone_number: '',
          url: 'https://www.krict.re.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        //대구
        PostModel(
          name: '대구경북과학기술원(대구)',
          phone_number: '',
          url: 'https://www.dgist.ac.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),

        PostModel(
          name: '대구기계부품연구원(대구)',
          phone_number: '',
          url: 'https://www.dmi.re.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),

        PostModel(
          name: '한국산업기술평가관리원(대구)',
          phone_number: '',
          url: 'https://www.keit.re.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        //경상남도
        PostModel(
          name: '재료연구소(경상남도)',
          phone_number: '',
          url: 'https://www.kims.re.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),

        PostModel(
          name: '한국전기연구원(경상남도)',
          phone_number: '',
          url: 'https://www.keri.re.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),

        PostModel(
          name: '한국산업기술시험원(경상남도)',
          phone_number: '',
          url: 'https://www.ktl.re.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),

        PostModel(
          name: '한국세라믹기술원(경상남도)',
          phone_number: '',
          url: 'https://www.kicet.re.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        //기타
        PostModel(
          name: '한국테크노파크진흥회(기타)',
          phone_number: '',
          url: 'https://www.technopark.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
      ],
    ),
    // CALL
    InnerList(
      name: 'Call',
      children: [
        PostModel(
          name: '교무처',
          phone_number: '0221232090',
          url: '',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '커리어연세',
          phone_number: '0221236677',
          url: '',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '신소재공학과 사무실',
          phone_number: '0221232830',
          url: '',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '연세대학교',
          phone_number: '15991885',
          url: '',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
      ],
    ),
    //YOUTUBE
    InnerList(
      name: 'Youtube',
      children: [],
    ),
    //OTHER
    InnerList(
      name: 'Other',
      children: [
        PostModel(
          name: 'Archive(정보수집)',
          phone_number: '',
          url: 'https://archive.org/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'B-ok(원서)',
          phone_number: '',
          url: 'https://b-ok.cc/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'Hyeopwork(협업)',
          phone_number: '',
          url: 'https://hyeopwork.com/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'Gen_lib(원서)',
          phone_number: '',
          url: 'https://gen.lib.rus.ec/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'Scholar(논문)',
          phone_number: '',
          url: 'https://scholar.google.co.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'Sci-Hub(논문)',
          phone_number: '',
          url: 'https://sci-hub.se/ ',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'Slader(문제풀이)',
          phone_number: '',
          url: 'www.slader.com',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: 'Thesaurus(유사단어)',
          phone_number: '',
          url: 'https://www.thesaurus.com/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '채용 - 캐치',
          phone_number: '',
          url: 'https://www.catch.co.kr/NCS/RecruitInformation',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '채용 - 사람인',
          phone_number: '',
          url: 'https://www.saramin.co.kr/zf_user/jobs/list/domestic',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '채용 - 원티드',
          phone_number: '',
          url: 'https://www.wanted.co.kr/jobsfeed',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '채용 - 인크루트',
          phone_number: '',
          url: 'https://www.incruit.com/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '채용 - 잡코리아',
          phone_number: '',
          url: 'https://www.jobkorea.co.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '자격증 - 해커스영어',
          phone_number: '',
          url: 'https://www.hackers.co.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '자격증 - 해커스 공기업',
          phone_number: '',
          url: 'https://public.hackers.com/A_public/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '자격증 - 에듀윌',
          phone_number: '',
          url: 'http://www.eduwill.net/Basic/global_main.asp',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '자격증 - 에듀윌',
          phone_number: '',
          url: 'https://hrd.tomatopass.com/main.do',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '자격증 - 인강드림',
          phone_number: '',
          url: 'http://www.ingangdream.com/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '취업커뮤 - 잡다',
          phone_number: '',
          url: 'https://www.jobda.im/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '취업커뮤 - 스펙업',
          phone_number: '',
          url: 'https://cafe.naver.com/specup',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '취업커뮤 - 딱공기업',
          phone_number: '',
          url: 'https://cafe.naver.com/gamnyang',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '취업커뮤 - 독취사',
          phone_number: '',
          url: 'https://cafe.naver.com/dokchi',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '대외 - 링커리어',
          phone_number: '',
          url: 'https://linkareer.com/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '대외 - 위비티',
          phone_number: '',
          url: 'https://www.wevity.com/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '대외 - 코멘토',
          phone_number: '',
          url: 'https://comento.kr/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '뉴스레터 - 뉴닉(시사)',
          phone_number: '',
          url: 'https://newneek.co/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '뉴스레터 - 데일리바이트(경제)',
          phone_number: '',
          url: 'https://mydailybyte.com/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
        PostModel(
          name: '뉴스레터 - 커피팟(해외)',
          phone_number: '',
          url: 'https://coffeepot.me/',
          lab_url: '',
          professor_url: '',
          category: '',
        ),
      ],
    ),
  ];

  List<InnerList> get outsourceList => _list;

  set setList(List<InnerList> newList) => _list = newList;
}
